"""Domain constants for JARVIS work management.

These values intentionally do not depend on Codex. Providers are adapters behind
this domain model so the rest of JARVIS remains provider-agnostic.
"""

PROJECT_STATUSES = {"ACTIVE", "PAUSED", "COMPLETED", "ARCHIVED"}
TASK_STATUSES = {"PLANNED", "READY", "RUNNING", "BLOCKED", "COMPLETED", "CANCELLED"}
RUN_STATUSES = {"QUEUED", "RUNNING", "WAITING_FOR_USER", "SUCCEEDED", "FAILED", "TIMED_OUT", "CANCELLED"}
SESSION_STATUSES = {"STARTING", "ACTIVE", "WAITING", "COMPLETED", "FAILED", "CANCELLED"}

EVENT_TYPES = {
    "PROJECT_CREATED",
    "TASK_CREATED",
    "RUN_CREATED",
    "RUN_STARTED",
    "TURN_STARTED",
    "AGENT_MESSAGE_DELTA",
    "AGENT_MESSAGE_COMPLETED",
    "TOOL_STARTED",
    "TOOL_COMPLETED",
    "COMMAND_STARTED",
    "COMMAND_COMPLETED",
    "APPROVAL_REQUIRED",
    "APPROVAL_GRANTED",
    "APPROVAL_REJECTED",
    "TURN_COMPLETED",
    "RUN_COMPLETED",
    "RUN_FAILED",
    "RUN_CANCELLED",
    "HANDOVER_CREATED",
    "SESSION_ROTATED",
}

APPROVAL_STATUSES = {"PENDING", "APPROVED", "REJECTED", "SUPERSEDED"}
ARTIFACT_TYPES = {"SPEC", "PLAN", "OUTPUT", "LOG", "OTHER"}
