"""Domain constants for JARVIS work management."""

PROJECT_STATUSES = {"ACTIVE", "PAUSED", "COMPLETED", "ARCHIVED"}
TASK_STATUSES = {"PLANNED", "READY", "RUNNING", "BLOCKED", "COMPLETED", "CANCELLED"}
RUN_STATUSES = {"QUEUED", "RUNNING", "WAITING_FOR_USER", "SUCCEEDED", "FAILED", "TIMED_OUT", "CANCELLED"}

# ROTATING is a recoverable transition state. ROTATED means the provider
# thread was successfully replaced and the old session must not be resumed.
SESSION_STATUSES = {
    "STARTING",
    "ACTIVE",
    "WAITING",
    "COMPLETED",
    "ROTATING",
    "ROTATED",
    "FAILED",
    "CANCELLED",
}

EVENT_TYPES = {
    "PROJECT_CREATED",
    "TASK_CREATED",
    "RUN_CREATED",
    "RUN_STARTED",
    "TURN_STARTED",
    "AGENT_MESSAGE_DELTA",
    "AGENT_MESSAGE_COMPLETED",
    "TOOL_STARTED",
    "TOOL_COMPLETED",
    "COMMAND_STARTED",
    "COMMAND_COMPLETED",
    "APPROVAL_REQUIRED",
    "APPROVAL_GRANTED",
    "APPROVAL_REJECTED",
    "TURN_COMPLETED",
    "RUN_COMPLETED",
    "RUN_FAILED",
    "RUN_CANCELLED",
    "HANDOVER_CREATED",
    "SESSION_ROTATED",
}

APPROVAL_STATUSES = {"PENDING", "APPROVED", "REJECTED", "SUPERSEDED"}
ARTIFACT_TYPES = {"SPEC", "PLAN", "OUTPUT", "LOG", "OTHER"}
